version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ssm-user/app/step2/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ssm-user
    group: ssm-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ssm-user